export { default as WelcomeView } from './WelcomeView'
export { default as DishSearchView } from './DishSearchView'
export { default as DishDetailsView } from './DishDetailsView'
export { default as RecipesView } from './RecipesView'
export { default as TotalPriceView } from './TotalPriceView'